# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goodhosts < Formula
  desc "A utility for editing your hosts file with single entries or blocks of entries."
  homepage "https://github.com/ChrisWiegman/goodhosts"
  version "4.1.1"
  license "MIT license"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/goodhosts/releases/download/v4.1.1/goodhosts_macos_x86_64.zip"
      sha256 "33324b1a629618c9281a99853c2c8cbbf231c05cfa7a387a62de59a008d04825"

      def install
        bin.install "goodhosts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ChrisWiegman/goodhosts/releases/download/v4.1.1/goodhosts_macos_arm64.zip"
      sha256 "9ed3bc0f19d9f05707f75a896b252967a57249ca474d2b31f3a4ba178db55035"

      def install
        bin.install "goodhosts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/goodhosts/releases/download/v4.1.1/goodhosts_linux_x86_64.zip"
      sha256 "6832a0d1910e4a2e605e954ba823a3b6ce5855d69c74fda37f849d8ecc9bf581"

      def install
        bin.install "goodhosts"
      end
    end
  end

  test do
    system "#{bin}/goodhosts version"
  end
end
