# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goodhosts < Formula
  desc "A utility for editing your hosts file with single entries or blocks of entries."
  homepage "https://github.com/ChrisWiegman/goodhosts"
  version "4.1.0"
  license "MIT license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ChrisWiegman/goodhosts/releases/download/4.1.0/goodhosts_4.1.0_macos_arm64.zip"
      sha256 "79f131c5f301dc82531a454ddb7c719f5c1bac34db5d62affe049f2b761b9fba"

      def install
        bin.install "goodhosts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/goodhosts/releases/download/4.1.0/goodhosts_4.1.0_macos_x86_64.zip"
      sha256 "5d9c3ca8a1bf83aeb72fc41d4420af164b85a90a1f1272b953962f1d6b710b82"

      def install
        bin.install "goodhosts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/goodhosts/releases/download/4.1.0/goodhosts_4.1.0_linux_x86_64.zip"
      sha256 "78c69acbc681ab977b04fcfa90745757fbac7d71298af3b9de43e066e8ab4706"

      def install
        bin.install "goodhosts"
      end
    end
  end

  test do
    system "#{bin}/goodhosts version"
  end
end
