# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goodhosts < Formula
  desc "A utility for editing your hosts file with single entries or blocks of entries."
  homepage "https://github.com/ChrisWiegman/goodhosts"
  version "4.1.3"
  license "MIT license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ChrisWiegman/goodhosts/releases/download/v4.1.3/goodhosts_macos_arm64.zip"
      sha256 "33c848a795528894d5fa8182544bdaa1540b552f9c4b4c93bc4201612af3dd0b"

      def install
        bin.install "goodhosts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/goodhosts/releases/download/v4.1.3/goodhosts_macos_x86_64.zip"
      sha256 "b3602362a02042375005f9a6eae40d61f24f8745ed4bf3b877a05d5cee55d8b7"

      def install
        bin.install "goodhosts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/goodhosts/releases/download/v4.1.3/goodhosts_linux_x86_64.zip"
      sha256 "ae1fd7f07500baa86b0333df42cabe9c1ba442e8e4fe6566717e94c67cd81b8e"

      def install
        bin.install "goodhosts"
      end
    end
  end

  test do
    system "#{bin}/goodhosts version"
  end
end
